
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Download, FileText, ArrowLeft, Copy, Check } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface ReportDisplayProps {
  reportContent: string;
  symptoms: string;
}

export const ReportDisplay = ({ reportContent, symptoms }: ReportDisplayProps) => {
  const [isCopied, setIsCopied] = useState(false);
  const { toast } = useToast();

  const downloadAsPDF = () => {
    // Format the report content for better readability
    const formattedContent = reportContent
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>') // Bold text
      .replace(/\*(.*?)\*/g, '<em>$1</em>') // Italic text
      .replace(/\n\n/g, '</p><p>') // Paragraphs
      .replace(/\n/g, '<br>'); // Line breaks

    // Create a comprehensive HTML document for PDF
    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Medical Analysis Report</title>
          <meta charset="UTF-8">
          <style>
            body { 
              font-family: 'Times New Roman', serif; 
              line-height: 1.6; 
              margin: 40px; 
              color: #333;
              background: white;
            }
            .header { 
              text-align: center; 
              margin-bottom: 40px; 
              border-bottom: 3px solid #2563eb;
              padding-bottom: 20px;
            }
            .header h1 { 
              color: #2563eb; 
              font-size: 28px;
              margin: 0;
              font-weight: bold;
            }
            .date { 
              text-align: right; 
              margin-bottom: 30px; 
              color: #6b7280; 
              font-style: italic;
            }
            .disclaimer { 
              background-color: #fef3c7; 
              padding: 20px; 
              border-left: 6px solid #f59e0b; 
              margin: 30px 0; 
              border-radius: 4px;
            }
            .disclaimer strong {
              color: #92400e;
            }
            .content {
              font-size: 14px;
              line-height: 1.8;
            }
            .content p {
              margin: 12px 0;
            }
            .content strong {
              color: #1e40af;
            }
            .footer {
              margin-top: 50px;
              padding-top: 20px;
              border-top: 2px solid #e5e7eb;
              font-size: 12px;
              color: #6b7280;
              text-align: center;
            }
            @media print {
              body { margin: 20px; }
              .no-print { display: none; }
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Medical Analysis Report</h1>
            <p style="margin: 10px 0 0 0; color: #6b7280;">AI-Assisted Medical Assessment</p>
          </div>
          
          <div class="date">
            Generated on: ${new Date().toLocaleDateString('en-US', { 
              weekday: 'long', 
              year: 'numeric', 
              month: 'long', 
              day: 'numeric' 
            })} at ${new Date().toLocaleTimeString()}
          </div>

          <div class="disclaimer">
            <strong>IMPORTANT MEDICAL DISCLAIMER:</strong> This report is generated using artificial intelligence analysis and is intended for informational purposes only. This document should be reviewed by a qualified healthcare professional and is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.
          </div>

          <div class="content">
            <p><strong>Chief Complaint:</strong> ${symptoms}</p>
            <hr style="margin: 20px 0; border: none; border-top: 1px solid #e5e7eb;">
            <p>${formattedContent}</p>
          </div>

          <div class="footer">
            <p>This report was generated by an AI medical analysis system.</p>
            <p>Report ID: MR-${Date.now()}</p>
          </div>
        </body>
      </html>
    `;

    // Create blob and download
    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Medical-Report-${new Date().toISOString().split('T')[0]}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Report Downloaded",
      description: "Your medical report has been downloaded as an HTML file that can be converted to PDF.",
    });
  };

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(reportContent);
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 2000);
      
      toast({
        title: "Report Copied",
        description: "The report content has been copied to your clipboard.",
      });
    } catch (error) {
      toast({
        title: "Copy Failed",
        description: "Failed to copy report to clipboard.",
        variant: "destructive"
      });
    }
  };

  const goBack = () => {
    window.location.reload(); // Simple way to go back to analysis view
  };

  return (
    <div className="space-y-6">
      <Card className="bg-slate-800/80 border-slate-700/50 backdrop-blur-sm">
        <CardHeader>
          <CardTitle className="flex items-center justify-between text-white">
            <div className="flex items-center gap-3">
              <FileText className="w-6 h-6 text-blue-400" />
              Medical Report Generated
            </div>
            <div className="flex gap-2">
              <Button 
                onClick={goBack}
                variant="outline"
                size="sm"
                className="border-slate-600 text-slate-300 hover:bg-slate-700"
              >
                <ArrowLeft className="w-4 h-4 mr-2" />
                Back to Analysis
              </Button>
              <Button 
                onClick={copyToClipboard}
                variant="outline"
                size="sm"
                className="border-slate-600 text-slate-300 hover:bg-slate-700"
              >
                {isCopied ? (
                  <Check className="w-4 h-4 mr-2" />
                ) : (
                  <Copy className="w-4 h-4 mr-2" />
                )}
                {isCopied ? 'Copied!' : 'Copy'}
              </Button>
              <Button 
                onClick={downloadAsPDF}
                className="bg-gradient-to-r from-green-500 to-emerald-500 hover:from-green-600 hover:to-emerald-600 text-white"
                size="sm"
              >
                <Download className="w-4 h-4 mr-2" />
                Download Report
              </Button>
            </div>
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="bg-white p-8 rounded-lg text-gray-900 max-h-[600px] overflow-y-auto shadow-inner">
            <div className="text-center mb-8">
              <h1 className="text-3xl font-bold text-blue-600 mb-2">Medical Analysis Report</h1>
              <p className="text-gray-600 text-lg">AI-Assisted Medical Assessment</p>
              <p className="text-gray-500 text-sm mt-2">Generated on {new Date().toLocaleDateString()}</p>
            </div>
            
            <div className="bg-yellow-50 border-l-4 border-yellow-400 p-6 mb-8 rounded-r-lg">
              <p className="text-sm text-yellow-800">
                <strong>IMPORTANT:</strong> This report is generated using AI analysis and should be reviewed by a qualified healthcare professional. This is not a substitute for professional medical advice, diagnosis, or treatment.
              </p>
            </div>

            <div className="mb-6 p-4 bg-blue-50 rounded-lg">
              <h3 className="font-semibold text-blue-800 mb-2">Chief Complaint:</h3>
              <p className="text-blue-700">{symptoms}</p>
            </div>
            
            <hr className="my-6 border-gray-300" />
            
            <div className="prose prose-sm max-w-none">
              <div className="whitespace-pre-wrap text-gray-800 leading-relaxed">
                {reportContent}
              </div>
            </div>

            <div className="mt-8 pt-6 border-t border-gray-200 text-center text-xs text-gray-500">
              <p>Report ID: MR-{Date.now()}</p>
              <p>Generated by AI Medical Analysis System</p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};
